### ISSUE TITLE
When adding NuGet package to my Project, Debugging fails with:

### ISSUE THREAD

**Issue by HisashiASM** [Const-me/Whisper#66]
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'WhisperNet, Version=1.10.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
  Source=ASTRO
  StackTrace:
   at ASTRO.Views.HomePage..ctor() in E:\Apps\ASTRO\ASTRO\Views\HomePage.xaml.cs:line 79
   at ASTRO.ASTRO_XamlTypeInfo.XamlTypeInfoProvider.Activate_51_HomePage() in E:\Apps\ASTRO\ASTRO\obj\x86\Debug\net7.0-windows10.0.19041.0\win10-x86\XamlTypeInfo.g.cs:line 437
   at ASTRO.ASTRO_XamlTypeInfo.XamlUserType.ActivateInstance() in E:\Apps\ASTRO\ASTRO\obj\x86\Debug\net7.0-windows10.0.19041.0\win10-x86\XamlTypeInfo.g.cs:line 3326
   at ABI.Microsoft.UI.Xaml.Markup.IXamlType.Do_Abi_ActivateInstance_13(IntPtr thisPtr, IntPtr* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IFrameMethods.Navigate(IObjectReference _obj, Type sourcePageType, Object parameter)
   at Microsoft.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter)
   at ASTRO.Services.NavigationService.NavigateTo(String pageKey, Object parameter, Boolean clearNavigation) in E:\Apps\ASTRO\ASTRO\Services\NavigationService.cs:line 92
   at ASTRO.Activation.DefaultActivationHandler.<HandleInternalAsync>d__3.MoveNext() in E:\Apps\ASTRO\ASTRO\Activation\DefaultActivationHandler.cs:line 25
   at ASTRO.Activation.ActivationHandler`1.<HandleAsync>d__3.MoveNext() in E:\Apps\ASTRO\ASTRO\Activation\ActivationHandler.cs:line 16
   at ASTRO.Services.ActivationService.<HandleActivationAsync>d__6.MoveNext() in E:\Apps\ASTRO\ASTRO\Services\ActivationService.cs:line 57
   at ASTRO.Services.ActivationService.<ActivateAsync>d__5.MoveNext() in E:\Apps\ASTRO\ASTRO\Services\ActivationService.cs:line 37
   at ASTRO.App.<OnLaunched>d__9.MoveNext() in E:\Apps\ASTRO\ASTRO\App.xaml.cs:line 98

```

**Comment by HisashiASM** [comment]
Mmmhph, VS2022 lied to me saying it was in x64, when it was still building x86
